### PR TITLE
updated to k6 v0.39.0

### PR DESCRIPTION
**Pull request by phsym**
To support latest k6 version (v0.39.0), package `go.k6.io/k6/stats` has been renamed to `go.k6.io/k6/metrics`.

I also updated logrus and prometheus client dependencies to latest versions

### CODE REVIEW

**Comment by phsym** [comment]
Without this change, the extension does not work on latest k6 version

**Comment by KnechtionsCoding** [comment]
@phsym I did fork: https://github.com/KnechtionsCoding/xk6-prometheus and updated the package name so that it can compile and be used properly. It should be updated to work on the latest k6 version and uses your contribution.

**Comment by szkiba** [comment]
@phsym Thank you for your contribution. Sorry for delay, I had no time for these project in the past period. Now I'm back.

**Comment by szkiba** [comment]
@KnechtionsCoding I'm back :) I'm glad that you found this project important in work.

**Pull request merged**
